change canary build to noarch
conda/conda-index pull request #99
Opened 2023-03-28 17:28 UTC by dholth

### Description

Canary build failed due to wrong subdir; the first party recipe is noarch. Will it succeed in noarch?

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-03-30 20:31 UTC, jezdez requested changes
Just minor nits, nice!

2023-03-30 20:31 UTC, jezdez commented on .github/workflows/canary-weekly.yml
> +      github.event_name != 'schedule' || !github.event.repository.fork
I'd prefer to encapsulate it like this:

```suggestion
    # - this is a fork and manually-triggered, or
    # - this is the main repo, and
    # - we are on the main (or feature) branch
    if: >-
      (
        github.event.repository.fork
        && github.event_name == 'workflow_dispatch'
      )
      || (
        !github.event.repository.fork
        && (
          github.ref_name == 'main'
          || startsWith(github.ref_name, 'feature/')
        )
      )

```

2023-03-30 20:52 UTC, dholth commented on .github/workflows/canary-weekly.yml
> +    - cron: "17 14 * * WED"
I picked it as being ~morning for me.

Check out the runtimes on this https://github.com/dholth/conda-index/actions . This project's unit tests take about 142 seconds.

2023-04-03 19:51 UTC, dbast approved these changes

2023-04-03 19:51 UTC, merged

2023-04-03 19:51 UTC, sven6002 reviewed
Looks good to me..